config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}, controllers: { sessions: "users/sessions" }

  resources :users, except: :index
  resources :service_providers, only: :create

  resources :properties do
    resources :items, path: 'notes'
    resources :users
    resources :service_providers, path: 'contacts'
  end

  root 'home#index'
  get 'privacy' => 'home#privacy'
  get 'terms_of_service' => 'home#tos'
  get 'about' => 'home#about'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :item_users
  has_many :items, through: :item_users
  has_many :property_users
  has_many :properties, through: :property_users
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_property

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def index
    @users = @property.users
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user           = User.find_or_initialize_by(user_params)
    @user.password  = SecureRandom.hex(10) unless @user.encrypted_password?
    Mailer.invitation(@user, current_user).deliver_now

    respond_to do |format|
      if @user.save
        find_or_create_property_user if @property
        format.html { redirect_to property_users_path(@property), notice: "#{@user.name} was successfully invited." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to property_users_path(@property), alert: "There was a problem creating #{user_params[:email]}." }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        find_or_create_property_user if @property
        format.html { redirect_to property_users_path(@property), notice: "#{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def find_or_create_property_user
    PropertyUser.find_or_create_by(user_id: @user.id, property_id: @property.id, admin: true)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for([@property, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, autofocus: true %>
  </div>
  <div class="actions">
    <%= f.submit @user.persisted? ? 'Save' : 'Send invite', class: 'button' %>
  </div>
  <%= f.hidden_field :property_id, value: params[:property_id] %>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, "Housechief | Profile" %>
<div class="row listing-shadow">
  <div class="row">
    <div class="panel header-panel">
      <div class="large-12 columns">
        <h1>Edit <u><%= @user.name %></u></h1>
      </div>
    </div>
  </div>

  <div class="row listing-shadow">
    <div class="columns large-12 form-padding-large">
      <%= render 'form' %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-12">
      <%= link_to 'Back', property_path(@property) %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row listing-shadow">
  <div class="row">
    <div class="panel header-panel">
      <div class="large-12 columns">
        <h1><%= @property.name %> Admins</h1>
      </div>
    </div>
  </div>

  <div class="row listing-shadow">
    <div class="columns large-12">
      <% @property.users.each do |user| %>
        <div class="row listing-row">
          <div class="large-2 columns small-3"><img src="http://placehold.it/80x80&text=[img]"/></div>
          <div class="large-10 columns">
            <p><strong><%= user.name %></strong></p>
            <p><%= user.email %></p>
          </div>
        </div>
        <hr/>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-12">
      <%= link_to 'Back', property_path(@property) %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :title, "Housechief | New Admin" %>

<div class="row listing-shadow">
  <div class="row">
    <div class="panel header-panel">
      <div class="large-12 columns">
        <h1>New Admin</h1>
        <p>Adds an admin to the <%= @property.name %> account. Create contacts for electricians, plumbers, contractors, etc. on the <u><a href="<%= new_property_service_provider_path(@property) %>">Contacts page</a></u>.</p>
      </div>
    </div>
  </div>

  <div class="row listing-shadow">
    <div class="columns large-12 form-padding-large">
      <%= render 'form' %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-12">
      <%= link_to 'Back', property_path(@property) %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title, "Housechief | #{@user.name}" %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>