config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}, controllers: { sessions: "users/sessions" }

  resources :users, except: :index
  resources :service_providers, only: :create

  resources :properties do
    resources :items, path: 'notes'
    resources :users
    resources :service_providers, path: 'contacts'
  end

  root 'home#index'
  get 'privacy' => 'home#privacy'
  get 'terms_of_service' => 'home#tos'
  get 'about' => 'home#about'

end

app/models/property.rb
class Property < ActiveRecord::Base

  has_many :property_users
  has_many :users, through: :property_users
  has_many :service_providers
  has_many :items
  has_many :attachments

  belongs_to :creator, class_name: 'User'

  after_create :create_property_user_on_creator

  MONTHS = %w(January February March April May June July August September October November December)

private

  def create_property_user_on_creator
    self.property_users.create(user_id: self.creator_id)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user!, except: [:new, :create, :index]
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = current_user.properties
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    # Rails.cache.fetch(@property.cache_key) do
    @items = @property.items.order('name ASC')
    # end
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property         = Property.new(property_params)
    @property.creator = current_user

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_property
    if @property.blank? || @property.id != params[:id]
      @property = Property.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def property_params
    params.require(:property).permit(:name, :address)
  end

  def authorize_user!
    if @property && current_user.properties.pluck(:id).exclude?(@property.id)
      redirect_to properties_path
    end
  end
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit 'Create new property',  class: 'button' %>
  </div>
<% end %>

app/views/properties/_item.html.erb
<% has_item_attachments = item.item_attachments.exists? %>
<div class="row">
  <div class="large-1 columns medium-1 small-2"><img src="<%= image_path('checkmark.png') %>"/></div>
  <div class="large-11 columns medium-11 small-10">
    <p class="item-title"><a href="<%= property_item_path(@property, item) %>">
      <strong><%= item.name %></strong></a>
    </p>
    <ul class="inline-list">
      <li class="item-notes"><%= simple_format truncate(item.notes, length: 200, escape: false) %></li>
      <% if item.last_maintenance_at? %>
        <li class="pull-right"><strong>Last update:</strong> <%= item.last_maintenance_at.strftime('%B %Y') %></li>
      <% end %>
      <% if item.frequency? %>
        <li class="pull-right"><strong>Frequency:</strong> <%= item.frequency.titleize %></li>
      <% end %>
      <% if has_item_attachments %>
        <% item.item_attachments.each do |item_attachment| %>
          <li class="pull-right">
            <%= render partial: 'shared/image', locals: { item_attachment: item_attachment, thumb: true} %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
<hr/>

app/views/properties/edit.html.erb
<% content_for :title, "Housechief | Edit Property" %>
<div class="row listing-shadow">
  <div class="row">
    <div class="panel header-panel">
      <div class="large-12 columns">
        <h1>Edit <u><%= @property.name %></u></h1>
      </div>
    </div>
  </div>

  <div class="row listing-shadow">
    <div class="columns large-12 form-padding-large">
      <%= render 'form' %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-12">
      <%= link_to 'Back', property_path(@property) %>
    </div>
  </div>
</div>

app/views/properties/index.html.erb
<% content_for :title, 'Housechief | Properties' %>
<div class="row">
  <div class="panel">
    <h1>Your properties</h1>
  </div>
</div>

<div class="row">

  <div class="large-offset-1 large-10 columns end">
    <% if @properties.blank? %>
      <div class="row margin-bottom-large">
        <div class="large-12 columns">
          <h3>First step, let's create a property.</h3>
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">
          <%= link_to 'Add a property', new_property_path, class: "button large" %>
        </div>
      </div>
    <% end %>

    <% @properties.each do |property| %>
      <div class="row">
        <div class="large-2 columns small-3"><img src="http://placehold.it/80x80&text=[img]"/></div>
        <div class="large-10 columns">

          <p><strong><%= property.name %></strong> <%= property.address %></p>
          <% if property.users.count > 1 %>
            <p>Members: <%= property.users.pluck(:name).join(", ") %></p>
          <% end %>
          <ul class="inline-list">
            <li><%= link_to 'View property', property %></li>
            <li><%= link_to 'Edit property', edit_property_path(property) %></li>
          </ul>

        </div>
      </div>
      <hr/>
    <% end %>
  </div>
</div>

app/views/properties/new.html.erb
<% content_for :title, "Housechief | New Property" %>
<div class="row listing-shadow">
  <div class="row">
    <div class="panel header-panel">
      <div class="large-12 columns">
        <h1>Add a new property</h1>
      </div>
    </div>
  </div>

  <div class="row listing-shadow">
    <div class="columns large-12 form-padding-large">
      <%= render 'form' %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-12">
      <%= link_to 'Back', properties_path %>
    </div>
  </div>
</div>

app/views/properties/show.html.erb
<% content_for :title, "Housechief | Notes" %>

<div class="row first-row listing-shadow">
  <div class="large-offset-1 large-10 columns end">
    <% if @items.blank? %>
      <div class="row margin-bottom-large">
        <div class="large-12 columns">
          <h3>Create a note to track info or share to-do's.</h3>
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">
          <%= link_to 'Create a note', new_property_item_path(@property), class: "button large" %>
        </div>
      </div>
    <% else %>
      <% @items.each do |item| %>
        <%= render partial: 'item', locals: {item: item} %>
      <% end %>
    <% end %>
  </div>

</div>