config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}, controllers: { sessions: "users/sessions" }

  resources :users, except: :index
  resources :service_providers, only: :create

  resources :properties do
    resources :items, path: 'notes'
    resources :users
    resources :service_providers, path: 'contacts'
  end

  root 'home#index'
  get 'privacy' => 'home#privacy'
  get 'terms_of_service' => 'home#tos'
  get 'about' => 'home#about'

end

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-content">
    <div class="row">
      <div class="columns small-12 end">
        <ul class="inline-list right">
          <% if @property && @property.persisted? %>
            <li><%= link_to 'New note', new_property_item_path(@property) %></li>
            <li><%= link_to 'Property settings', edit_property_path(@property) %></li>
          <% else %>
            <li>© HouseChief <%= Time.now.strftime('%Y') %></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Privacy Policy', privacy_path %></li>
            <li><%= link_to 'Terms of Service', terms_of_service_path %></li>
          <% end %>
      </div>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_image.html.erb
<%  attachment_file = item_attachment.file
    file_path = thumb == true ? attachment_file.thumb.url : attachment_file.url
    image_path = item_attachment.is_image? ? file_path : attachment_file.default_url
%>

<%= image_tag(image_path) %>

app/views/shared/_topbar.html.erb
<nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: [small,medium,large]">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Housechief</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%  items_active = controller_name == 'properties' && action_name == 'show'
          sp_active = controller_name == 'service_providers'
          settings_active = controller_name == 'properties' && action_name == 'edit'
      %>
      <% if @property.present? && @property.persisted? %>
        <li class="<%= 'active' if items_active %>"><a href="<%= property_path(@property) %>">Notes</a></li>
        <li class="<%= 'active' if sp_active %>"><a href="<%= property_service_providers_path(@property) %>">Contacts</a></li>
        <li class="<%= 'active' if settings_active %>"><a href="<%= edit_property_path(@property) %>">Settings</a></li>
        <li class="has-dropdown">
          <a href="#"><%= image_tag('add-note-white.png') %></a>
          <ul class="dropdown">
            <li><a href="<%= new_property_item_path(@property) %>">New Note</a></li>
            <li><%= link_to 'New Contact', new_property_service_provider_path(@property) %></li>
            <li><%= link_to 'Add Admin', new_property_user_path(@property) %></li>
          </ul>
        </li>
      <% end %>
      <% if current_user %>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
      <% end %>
    </ul>
  </section>
</nav>