config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}, controllers: { sessions: "users/sessions" }

  resources :users, except: :index
  resources :service_providers, only: :create

  resources :properties do
    resources :items, path: 'notes'
    resources :users
    resources :service_providers, path: 'contacts'
  end

  root 'home#index'
  get 'privacy' => 'home#privacy'
  get 'terms_of_service' => 'home#tos'
  get 'about' => 'home#about'

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :property, touch: true
  has_many :item_attachments, dependent: :destroy
accepts_nested_attributes_for :item_attachments, allow_destroy: true
  has_many :item_users
  has_many :users, through: :item_users

  FREQUENCY = {
    daily:      1.day.to_i,
    weekly:     1.week.to_i,
    monthly:    1.month.to_i,
    quarterly:  3.months.to_i,
    biannually: 6.months.to_i,
    annually:   1.year.to_i
  }.with_indifferent_access

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_property
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_item_attachments, only: [:show, :edit, :update, :destroy]
  before_action :format_attachment_params, only: [:create, :update]
  before_action :format_last_maintenance_at, only: [:create, :update]

  # GET /items
  # GET /items.json
  def index
    @items = @property.items
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = @property.items.find_by_id(params[:id])
  end

  # GET /items/new
  def new
    @item = @property.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = @property.items.new(item_params)

    respond_to do |format|
      if @item.save
        process_attachments
        format.html { redirect_to @item, notice: "#{@item.name} was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        process_attachments
        format.html { redirect_to @item, notice: "#{@item.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to property_path(@property), notice: "#{@item.name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

private
  def set_property
    @property = Property.find(params[:property_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = @property.items.find(params[:id])
  end

  def set_item_attachments
    @item_attachments = @item.item_attachments
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    @item_params = params.require(:item).permit(:name, :notes, :frequency, :last_maintenance_at, {attachments: []})
  end

  def format_last_maintenance_at
    return unless params[:item][:last_maintenance_at][:month].present?
    params[:item][:last_maintenance_at] = Time.parse("#{params[:item][:last_maintenance_at][:month]} #{params[:item][:last_maintenance_at][:year]}").to_s
  end

  def format_attachment_params
    load_attachments if params[:item][:attachments].present?
    remove_attachments if params[:remove_attachments].present?
  end

  def load_attachments
    @attachment_params = params[:item].delete(:attachments)
  end

  def remove_attachments
    params[:remove_attachments].each do |attachment_id|
      item_attachment = @item.item_attachments.find(attachment_id.to_i)
      item_attachment.destroy
    end
  end

  def process_attachments
    return unless @attachment_params
    @attachment_params.each { |f| @item.item_attachments.create(file: f) }
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for [@property, @item] do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>

  </div>
  <div class="row first-row">
    <div class="columns large-12">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-12">
      <%= f.label :notes %><br>
      <%= f.text_area :notes %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-7">
      <div class="row">
        <div class="columns large-12">
          <%= f.label :last_maintenance_at, 'Last maintenance' %>
        </div>
        <div class="columns large-4">
          <select name="item[last_maintenance_at][month]">
            <option value="" <%= 'selected' unless @item.last_maintenance_at %> >Select Month</option>
            <%= Property::MONTHS.each do |month| %>
              <option value="<%= month %>" <%= 'selected' if @item.last_maintenance_at && @item.last_maintenance_at.strftime('%B') == month %>><%= month %></option>
            <% end %>
          </select>
        </div>
        <div class="columns large-3">
          <select name="item[last_maintenance_at][year]">
            <option value="" <%= 'selected' unless @item.last_maintenance_at %> >Select Year</option>
            <%= (1990..Time.now.year).to_a.reverse.each do |year| %>
              <option value="<%= year %>" <%= 'selected' if @item.last_maintenance_at && @item.last_maintenance_at.strftime('%Y') == year %>><%= year %></option>
            <% end %>
          </select>
        </div>
        <div class="columns large-5">
          <select name="item[frequency]">
            <option value="" selected="selected">Frequency (optional)</option>
            <option value="daily">Daily</option>
            <option value="weekly">Weekly</option>
            <option value="monthly">Monthly</option>
            <option value="quarterly">Quarterly</option>
            <option value="biannually">Twice per year</option>
            <option value="annually">Annually</option>
          </select>
        </div>
      </div>
    </div>

    <div class="columns large-5">
      <%= f.label :attachments %>
      <div class="attachment-button">
        <%= f.file_field :attachments, multiple: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="columns large-12">
      <% if @item.item_attachments.present? %>
        <div class="row">
          <% attachment_count = @item_attachments.count %>
          <% @item_attachments.each_with_index do |item_attachment, index| %>
            <div class="columns large-3 <%= 'end' if attachment_count == (index + 1) %>">
              <label for="remove_attachment">Remove file:
                <input type="checkbox" name="remove_attachments[]" value="<%= item_attachment.id %>">
              </label>
              <div style="padding:10px;">
                <!-- TODO if PDF add PDF thumbnail placeholder -->
                <%= image_tag(item_attachment.file.url) %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="actions">
    <%= f.submit @item.new_record? ? 'Create Note' : 'Update Note', class: 'button' %>
  </div>
<% end %>

<%= javascript_include_tag 'properties' %>

app/views/items/edit.html.erb
<div class="row listing-shadow">
  <div class="row">
    <div class="panel header-panel">
      <div class="large-12 columns">
        <h1>Edit <u><%= @item.name %></u></h1>
      </div>
    </div>
  </div>

  <div class="row listing-shadow">
    <div class="columns large-12 form-padding-large">
      <%= render 'form' %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-12">
      <%= link_to 'Show', property_item_path(@property, @item) %> |
      <%= link_to 'Back', property_items_path %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<% content_for :title, "Housechief | [Admin View]" %>

<div class="row">
  <!-- <div class="columns large-12"> -->
    <h1>Notes</h1>
  <!-- </div> -->
</div>

<div class="row">
  <!-- <div class="columns large-12"> -->
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Notes</th>
          <th>Attachments</th>
          <th>Frequency</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @items.each do |item| %>
          <tr class="items-listing">
            <td>
              <a href="<%= property_item_path(@property, item) %>">
                <p><%= item.name %></p>
              </a>
            </td>
            <td>
              <a href="<%= property_item_path(@property, item) %>">
                <%= simple_format truncate(item.notes, length: 200, escape: false) %>
              </a>
            </td>
            <td>
              <% if item.item_attachments.exists? %>
                <% item.item_attachments.each do |item_attachment| %>
                  <%= render partial: 'shared/image', locals: {item_attachment: item_attachment, thumb: true} %>
                <% end %>
              <% end %>
            </td>
            <td><%= item.frequency %></td>
            <td><%= link_to 'Edit', edit_property_item_path(property_id: @property.id, id: item.id) %></td>
            <td><%= link_to 'Delete', property_item_path(property_id: @property.id, id: item.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <!-- </div> -->
</div>

<div class="row">
  <!-- <div class="columns large-12"> -->
    <%= link_to 'New note', new_property_item_path %>
  <!-- </div> -->
</div>

app/views/items/new.html.erb
<% content_for :title, "Housechief | New Note" %>

<div class="row listing-shadow">
  <div class="row">
    <div class="panel header-panel">
      <div class="large-12 columns">
        <h1>New note</h1>
      </div>
    </div>
  </div>

  <div class="row listing-shadow">
    <div class="columns large-12 form-padding-large">
      <%= render 'form' %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-12">
      <%= link_to 'Back', property_path(@property) %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-1 columns small-3 item-thumbnail-container">
        <%= image_tag('notebook.png', class: 'item-thumbnail') %>
      </div>
      <div class="large-11 columns">
        <div class="row">
          <div class="large-12 columns">
            <h2><strong><%= @item.name %></strong> <span class="edit-link">(<a href="<%= edit_property_item_path(@property, @item) %>">edit</a>)</span></h2>
            <p><%= simple_format @item.notes %></p>
          </div>
        </div>

        <div class="row">
          <div class="large-12 columns">
            <% if @item.frequency? %>
              <p><strong>Maintenance Frequency:</strong> <%= @item.frequency.titleize %></p>
            <% end %>
          </div>
        </div>

        <% if @item.last_maintenance_at %>
          <div class="row">
            <div class="large-3 columns">
              <p><strong>Last updated:</strong></p>
            </div>
            <div class="large-4 columns end">
              <%= @item.last_maintenance_at.strftime('%B %Y') %>
            </div>
          </div>
        <% end %>
        <% item_attachments_count = @item_attachments.size %>
        <% if item_attachments_count > 0 %>
          <h6>Attachments</h6>
          <div class="row">
            <% @item_attachments.each_with_index do |item_attachment, index| %>
              <% file = item_attachment.file %>
              <% last_attachment = item_attachments_count == (index + 1) %>
              <div class="columns large-3 small-3 file-link <%= 'end' if last_attachment %>">
                <a href="<%= file.url %>" type="<%= file.content_type %>" target="_blank">
                  <%= render partial: 'shared/image', locals: { item_attachment: item_attachment, thumb: false } %>
                  <% unless item_attachment.is_image? %>
                    <br><span class="download-label">Click to download</span>
                  <% end %>
                  <br><%= file.filename || file.file.filename %>
                </a>
              </div>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

</div>

<%= render partial: 'shared/footer' if @property %>

<%= javascript_include_tag 'properties' %>